### ISSUE TITLE
Artifact of Soul working incorrectly as of "The Devotion Update"

### ISSUE THREAD

**Issue by kking117** [WolfoIsBestWolf/ror2-FixedSpawnDissonance#2]
When killing an enemy that should spawn a Greater Soul Wisp it spawns a regular Greater Wisp, which when killed will spawn another Greater Wisp and so on. The same issue also happen with enemies that should spawn Archaic Soul Wisps on death. The Soul Wisps also seem to be weaker than usual, so maybe all the changes with it broke.

[LogOutput.log](https://github.com/WolfoIsBestWolf/ror2-FixedSpawnDissonance/files/15410908/LogOutput.log)

**Comment by WolfoIsBestWolf** [comment]
Mod did not load with the update so everything didn't work. Should be fixed in quick patch.
