### ISSUE TITLE
REX's entanglement debuff not being removed properly.

### ISSUE THREAD

**Issue by LostWarriorr** [WolfoIsBestWolf/ror2-FixedSpawnDissonance#4]
Whenever this mod (Vanilla Artifact Plus) is enabled the entanglement debuff that REX applies with his special is not removed if the entity in which it is initially attached to dies (if applicable).

Steps to reproduce:
- Attach Tangling growth to low health/small enemy.
- Kill enemy before the skill is over.
- The debuff is now applied permanently to enemies that were in the AoE.

![image](https://github.com/user-attachments/assets/889466bd-dc8d-464e-ae92-d6f41a230ba6)

**Comment by WolfoIsBestWolf** [comment]
very detailed ty, should be fixed now
